In [183]:
import csv
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from functools import reduce

In [189]:
CYData_df = pd.read_csv("combdata.csv")
CYData_df.head()

,State,Total Beds 2018,Participation 2018,Total Beds 2017,Participation 2017,Total Beds 2016,Participation 2016,Total Beds 2015,Participation 2015,Total Beds 2014,...,Total Beds 2012,Participation 2012,Total Beds 2011,Participation 2011,Total Beds 2010,Participation 2010,Total Beds 2009,Participation 2009,Unnamed: 21,Unnamed: 22
0,AK,1940.0,72.53%,1828.0,71.50%,1826.0,68.40%,1860.0,60.97%,1814.0,...,"1,877",83.50%,"1,939",81.90%,"1,805",74.00%,"1,697",74.50%,NaN,NaN
1,AL,3188.0,51.22%,3444.0,46.49%,3489.0,55.35%,3613.0,49.68%,3724.0,...,"4,297",48.20%,"4,497",51.80%,"4,221",43.70%,"4,065",42.20%,NaN,NaN
2,AR,2362.0,29.00%,2062.0,36.03%,2394.0,37.89%,2486.0,40.51%,2151.0,...,"2,662",64.60%,"2,710",67.20%,"2,700",69.10%,"1,802",74.70%,NaN,NaN
3,AZ,6683.0,69.01%,5880.0,78.06%,6942.0,77.83%,7473.0,76.01%,8873.0,...,"9,238",86.20%,"8,748",86.10%,"8,914",87.40%,"9,066",84.40%,NaN,NaN
4,CA,43548.0,64.57%,44473.0,57.88%,42351.0,67.60%,45929.0,65.59%,44035.0,...,"47,144",75.70%,"49,657",70.20%,"50,282",64.00%,"52,397",64.00%,NaN,NaN

In [157]:
# Sh09_df = pd.read_csv("2007-2018-HIC-Counts-by-State_2009.csv").rename(columns={'Total Year-Round Beds (ES,TH,SH)':'Total Beds 2009','HMIS Participation Rate (ES,TH,SH)':'Participation 2009'})
# # pd.DataFrame(Sh09_df)
# Sh10_df = pd.read_csv("2007-2018-HIC-Counts-by-State_2010.csv").rename(columns={'Total Year-Round Beds (ES,TH,SH)':'Total Beds 2010','HMIS Participation Rate (ES,TH,SH)':'Participation 2010'})
# # pd.DataFrame(Sh10_df)
# Sh11_df = pd.read_csv("2007-2018-HIC-Counts-by-State_2011.csv").rename(columns={'Total Year-Round Beds (ES,TH,SH)':'Total Beds 2011','HMIS Participation Rate (ES,TH,SH)':'Participation 2011'})
# # pd.DataFrame(Sh11_df)
# Sh12_df = pd.read_csv("2007-2018-HIC-Counts-by-State_2012.csv").rename(columns={'Total Year-Round Beds (ES,TH,SH)':'Total Beds 2012','HMIS Participation Rate (ES,TH,SH)':'Participation 2012'})
# # pd.DataFrame(Sh12_df)
# Sh13_df = pd.read_csv("2007-2018-HIC-Counts-by-State_2013.csv").rename(columns={'Total Year-Round Beds (ES,TH,SH)':'Total Beds 2013','HMIS Participation Rate (ES,TH,SH)':'Participation 2013'})
# # pd.DataFrame(Sh13_df)
# Sh14_df = pd.read_csv("2007-2018-HIC-Counts-by-State_2014.csv").rename(columns={'Total Year-Round Beds (ES,TH,SH)':'Total Beds 2014','HMIS Participation Rate (ES,TH,SH)':'Participation 2014'})
# # pd.DataFrame(Sh14_df)
# Sh15_df = pd.read_csv("2007-2018-HIC-Counts-by-State_2015.csv").rename(columns={'Total Year-Round Beds (ES,TH,SH)':'Total Beds 2015','HMIS Participation Rate (ES,TH,SH)':'Participation 2015'})
# # pd.DataFrame(Sh15_df)
# Sh16_df = pd.read_csv("2007-2018-HIC-Counts-by-State_2016.csv").rename(columns={'Total Year-Round Beds (ES,TH,SH)':'Total Beds 2016','HMIS Participation Rate (ES,TH,SH)':'Participation 2016'})
# # pd.DataFrame(Sh16_df)
# Sh17_df = pd.read_csv("2007-2018-HIC-Counts-by-State_2017.csv").rename(columns={'Total Year-Round Beds (ES,TH,SH)':'Total Beds 2017','HMIS Participation Rate (ES,TH,SH)':'Participation 2017'})
# # pd.DataFrame(Sh17_df)
# Sh18_df = pd.read_csv("2007-2018-HIC-Counts-by-State_2018.csv").rename(columns={'Total Year-Round Beds (ES,TH,SH)':'Total Beds 2018','HMIS Participation Rate (ES,TH,SH)':'Participation 2018'})
# # pd.DataFrame(Sh18_df)

In [162]:
# df_list0 = [Sh09_df, Sh10_df, Sh11_df]
# df_list2 = [Sh12_df, Sh13_df, Sh14_df]
# df_list3 = [Sh15_df, Sh16_df, Sh17_df]

In [159]:
# Shelters_09_df = Shelters_09_df.rename(columns={'Total Year-Round Beds (ES,TH,SH)':'Total Beds 2009','HMIS Participation Rate (ES,TH,SH)':'Participation 2009'})
# Shelters_10_df = Shelters_10_df.rename(columns={'Total Year-Round Beds (ES,TH,SH)':'Total Beds 2010','HMIS Participation Rate (ES,TH,SH)':'Participation 2010'})
# Shelters_11_df = Shelters_11_df.rename(columns={'Total Year-Round Beds (ES,TH,SH)':'Total Beds 2011','HMIS Participation Rate (ES,TH,SH)':'Participation 2011'})
# Shelters_12_df = Shelters_12_df.rename(columns={'Total Year-Round Beds (ES,TH,SH)':'Total Beds 2012','HMIS Participation Rate (ES,TH,SH)':'Participation 2012'})
# Shelters_13_df = Shelters_13_df.rename(columns={'Total Year-Round Beds (ES,TH,SH)':'Total Beds 2013','HMIS Participation Rate (ES,TH,SH)':'Participation 2013'})
# Shelters_14_df = Shelters_14_df.rename(columns={'Total Year-Round Beds (ES,TH,SH)':'Total Beds 2014','HMIS Participation Rate (ES,TH,SH)':'Participation 2014'})
# Shelters_15_df = Shelters_15_df.rename(columns={'Total Year-Round Beds (ES,TH,SH)':'Total Beds 2015','HMIS Participation Rate (ES,TH,SH)':'Participation 2015'})
# Shelters_16_df = Shelters_16_df.rename(columns={'Total Year-Round Beds (ES,TH,SH)':'Total Beds 2016','HMIS Participation Rate (ES,TH,SH)':'Participation 2016'})
# Shelters_17_df = Shelters_17_df.rename(columns={'Total Year-Round Beds (ES,TH,SH)':'Total Beds 2017','HMIS Participation Rate (ES,TH,SH)':'Participation 2017'})
# Shelters_18_df = Shelters_18_df.rename(columns={'Total Year-Round Beds (ES,TH,SH)':'Total Beds 2018','HMIS Participation Rate (ES,TH,SH)':'Participation 2018'})

In [173]:
# combined_total = pd.merge(Sh09_df, Sh10_df, on="State")

# combined_df1 = reduce(lambda one, two : pd.merge(one, two, on ="State"), [Sh09_df, Sh10_df, Sh11_df])
# combined_df2 = reduce(lambda three, four : pd.merge(three, four, on ="State"), [combined_df1, Sh12_df, Sh13_df])
# combined_df3 = reduce(lambda five, six : pd.merge(five, six, on ="State"), [combined_df2, Sh14_df, Sh15_df])
# combined_df4 = reduce(lambda seven, eight : pd.merge(seven, eight, on ="State"), [combined_df3, Sh16_df, Sh17_df])
# combined_df5 = reduce(lambda nine, ten : pd.merge(nine, ten, on ="State"), [combined_df4, Sh18_df])

# combined_df5.head()

,State,Total Beds 2009,"Total Non-DV Year-Round Beds (ES,TH,SH)_x","Total HMIS Year-Round Beds (ES,TH,SH)_x",Participation 2009,Total Emergency Shelter (ES) Beds (excluding seasonal+O/V)_x,Total Transitional Housing (TH) Beds_x,Total Safe Haven (SH) Beds_x,"Total Units for Households with Children (ES,TH)_x","Total Beds for Households with Children (ES,TH)_x",...,Total Year-Round Beds (OPH),Total Non-DV Year-Round Beds (OPH),Total HMIS Year-Round Beds (OPH),HMIS Participation Rate for Year-Round Beds (OPH),Total Units for Households with Children (OPH),Total Beds for Households with Children (OPH),Total Beds for Households without Children (OPH),Total Beds for Households with only Children (OPH),Dedicated Veteran Beds (OPH)_y,Dedicated Youth Beds (OPH)_y
0,AK,"1,697","1,235",920,74.50%,"1,115",582,0,199,651,...,71,71,71,100.00%,0,0,71,0,0,0
1,AL,"4,065","3,515","1,484",42.20%,"1,611","2,420",34,434,"1,349",...,0,0,0,.,0,0,0,0,0,0
2,AR,"1,802","1,330",994,74.70%,904,898,0,196,604,...,8,8,8,100.00%,0,0,8,0,0,0
3,AZ,"9,066","7,145","6,028",84.40%,"4,011","5,015",40,"1,540","5,390",...,1086,1086,1086,100.00%,259,901,185,0,29,10
4,CA,"52,397","45,819","29,311",64.00%,"20,221","31,969",207,"6,843","22,592",...,5062,5034,3458,68.31%,612,1774,3288,0,478,34

In [175]:
# merged_year_df = combined_df5[['State','Total Beds 2009','Participation 2009','Total Beds 2010','Participation 2010','Total Beds 2011','Participation 2011','Total Beds 2012','Participation 2012,]]
# merged_year_df

SyntaxError: EOL while scanning string literal (<ipython-input-175-9298dc71b0cb>, line 1)

In [ ]:
#'Total Beds 2009', 'Participation 2009', 'Total Beds 2010', 'Participation 2010', 'Total Beds 2011', 'Participation 2011', 'Total Beds 2012', 'Participation 2012', 'Total Beds 2013', 'Participation 2013', 'Total Beds 2014', 'Participation 2014', 'Total Beds 2015', 'Participation 2015', 'Total Beds 2016', 'Participation 2016','Total Beds 2017', 'Participation 2017', 'Total Beds 2018', 'Participation 2018']]

In [ ]:
# combined_F = pd.merge(combined_A, combined_B, on='State')
# combined_G= pd.merge(combined_C, combined_D, on='State')
# combined_H = pd.merge(combined_F, combined_G, on='State')

In [ ]:
# combined_years = pd.merge(combined_H, combined_E, on='State')

In [ ]:
# Shelters_11_df, Shelters_12_df, Shelters_13_df, Shelters_14_df, Shelters_15_df, Shelters_16_df, Shelters_17_df, Shelters_18_df