In [69]:
import csv
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from functools import reduce

In [70]:
Sh09_df = pd.read_csv("2007-2018-HIC-Counts-by-State_2009.csv", usecols=[0,1,4], header=0, names=["State","Total Beds 2009","Participation 2009"])
Sh10_df = pd.read_csv("2007-2018-HIC-Counts-by-State_2010.csv", usecols=[0,1,4], header=0, names=["State","Total Beds 2010","Participation 2010"])
Sh11_df = pd.read_csv("2007-2018-HIC-Counts-by-State_2011.csv", usecols=[0,1,4], header=0, names=["State","Total Beds 2011","Participation 2011"])
Sh12_df = pd.read_csv("2007-2018-HIC-Counts-by-State_2012.csv", usecols=[0,1,4], header=0, names=["State","Total Beds 2012","Participation 2012"])
Sh13_df = pd.read_csv("2007-2018-HIC-Counts-by-State_2013.csv", usecols=[0,1,4], header=0, names=["State","Total Beds 2013","Participation 2013"])
Sh14_df = pd.read_csv("2007-2018-HIC-Counts-by-State_2014.csv", usecols=[0,1,4], header=0, names=["State","Total Beds 2014","Participation 2014"])
Sh15_df = pd.read_csv("2007-2018-HIC-Counts-by-State_2015.csv", usecols=[0,1,4], header=0, names=["State","Total Beds 2015","Participation 2015"])
Sh16_df = pd.read_csv("2007-2018-HIC-Counts-by-State_2016.csv", usecols=[0,1,4], header=0, names=["State","Total Beds 2016","Participation 2016"])
Sh17_df = pd.read_csv("2007-2018-HIC-Counts-by-State_2018.csv", usecols=[0,1,4], header=0, names=["State","Total Beds 2017","Participation 2017"])
Sh18_df = pd.read_csv("2007-2018-HIC-Counts-by-State_2018.csv", usecols=[0,1,4], header=0, names=["State","Total Beds 2018","Participation 2018"])

In [78]:
df = pd.concat([Sh17_df,Sh18_df], ignore_index=True)
df

C:\Users\John Wright\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.

,Participation 2017,Participation 2018,State,Total Beds 2017,Total Beds 2018
0,72.53%,NaN,AK,1940.0,NaN
1,51.22%,NaN,AL,3188.0,NaN
2,29.00%,NaN,AR,2362.0,NaN
3,69.01%,NaN,AZ,6683.0,NaN
4,64.57%,NaN,CA,43548.0,NaN
5,48.37%,NaN,CO,7532.0,NaN
6,87.91%,NaN,CT,3417.0,NaN
7,88.56%,NaN,DC,6721.0,NaN
8,52.94%,NaN,DE,1122.0,NaN
9,71.23%,NaN,FL,19554.0,NaN
10,47.68%,NaN,GA,7363.0,NaN
11,63.57%,NaN,GU,140.0,NaN
12,92.97%,NaN,HI,3599.0,NaN
13,71.94%,NaN,IA,3026.0,NaN
14,34.32%,NaN,ID,1413.0,NaN
15,79.17%,NaN,IL,10210.0,NaN
16,54.09%,NaN,IN,5568.0,NaN
17,39.02%,NaN,KS,2599.0,NaN
18,52.97%,NaN,KY,2875.0,NaN
19,67.21%,NaN,LA,2647.0,NaN
20,89.71%,NaN,MA,17310.0,NaN
21,77.77%,NaN,MD,5529.0,NaN
22,82.04%,NaN,ME,2734.0,NaN
23,68.83%,NaN,MI,8531.0,NaN
24,73.47%,NaN,MN,6660.0,NaN
25,50.30%,NaN,MO,5624.0,NaN
26,0.00%,NaN,MP,30.0,NaN
27,58.29%,NaN,MS,1079.0,NaN
28,10.97%,NaN,MT,1376.0,NaN
29,66.72%,NaN,NC,7963.0,NaN
...,...,...,...,...,...
82,NaN,0.00%,MP,NaN,30.0
83,NaN,58.29%,MS,NaN,1079.0
84,NaN,10.97%,MT,NaN,1376.0
85,NaN,66.72%,NC,NaN,7963.0
86,NaN,67.22%,ND,NaN,726.0
87,NaN,58.95%,NE,NaN,2390.0
88,NaN,80.95%,NH,NaN,1349.0
89,NaN,83.50%,NJ,NaN,7099.0
90,NaN,38.16%,NM,NaN,1651.0
91,NaN,78.80%,NV,NaN,3033.0
92,NaN,85.15%,NY,NaN,88063.0
93,NaN,72.88%,OH,NaN,9269.0
94,NaN,58.52%,OK,NaN,3339.0
95,NaN,53.59%,OR,NaN,6419.0
96,NaN,71.45%,PA,NaN,12909.0
97,NaN,80.31%,PR,NaN,955.0
98,NaN,72.48%,RI,NaN,1003.0
99,NaN,61.95%,SC,NaN,3001.0
100,NaN,15.60%,SD,NaN,1090.0
101,NaN,48.13%,TN,NaN,5674.0
102,NaN,58.77%,TX,NaN,18006.0
103,NaN,65.46%,UT,NaN,2968.0
104,NaN,65.62%,VA,NaN,5303.0
105,NaN,33.17%,VI,NaN,205.0
106,NaN,66.81%,VT,NaN,937.0
107,NaN,65.51%,WA,NaN,15016.0
108,NaN,69.33%,WI,NaN,4721.0
109,NaN,64.97%,WV,NaN,1593.0
110,NaN,71.61%,WY,NaN,560.0
111,NaN,70.88%,Total,NaN,389622.0

In [65]:
dfs = [Sh09_df, Sh10_df, Sh11_df, Sh12_df, Sh13_df, Sh14_df, Sh15_df, Sh16_df, Sh17_df, Sh18_df]
comb_sh_df = reduce(lambda left,right:pd.merge(left,right,on="State"), dfs)
comb_sh_df.head()

,State,Total Beds 2009,Participation 2009,Total Beds 2010,Participation 2010,Total Beds 2011,Participation 2011,Total Beds 2012,Participation 2012,Total Beds 2013,...,Total Beds 2014,Participation 2014,Total Beds 2015,Participation 2015,Total Beds 2016,Participation 2016,Total Beds 2017,Participation 2017,Total Beds 2018,Participation 2018
0,AK,"1,697",74.50%,"1,805",74.00%,"1,939",81.90%,"1,877",83.50%,1895,...,1814,56.84%,1860,60.97%,1826,68.40%,1828,71.50%,1940,72.53%
1,AL,"4,065",42.20%,"4,221",43.70%,"4,497",51.80%,"4,297",48.20%,4077,...,3724,53.30%,3613,49.68%,3489,55.35%,3444,46.49%,3188,51.22%
2,AR,"1,802",74.70%,"2,700",69.10%,"2,710",67.20%,"2,662",64.60%,2561,...,2151,43.89%,2486,40.51%,2394,37.89%,2062,36.03%,2362,29.00%
3,AZ,"9,066",84.40%,"8,914",87.40%,"8,748",86.10%,"9,238",86.20%,8982,...,8873,68.33%,7473,76.01%,6942,77.83%,5880,78.06%,6683,69.01%
4,CA,"52,397",64.00%,"50,282",64.00%,"49,657",70.20%,"47,144",75.70%,45411,...,44035,70.57%,45929,65.59%,42351,67.60%,44473,57.88%,43548,64.57%

In [66]:
# combined_total = pd.merge(Sh09_df, Sh10_df, on="State")

# combined_df1 = reduce(lambda one, two : pd.merge(one, two, on ="State"), [Sh09_df, Sh10_df, Sh11_df])
# combined_df2 = reduce(lambda three, four : pd.merge(three, four, on ="State"), [combined_df1, Sh12_df, Sh13_df])
# combined_df3 = reduce(lambda five, six : pd.merge(five, six, on ="State"), [combined_df2, Sh14_df, Sh15_df])
# combined_df4 = reduce(lambda seven, eight : pd.merge(seven, eight, on ="State"), [combined_df3, Sh16_df, Sh17_df])
# combined_df5 = reduce(lambda nine, ten : pd.merge(nine, ten, on ="State"), [combined_df4, Sh18_df])

# combined_df5.head()

In [ ]:
# CYData_df = pd.read_csv("combdata.csv")
# CYData_df.head()
# pd.DataFrame(Sh18_df)

In [ ]:
# Sh09_df = pd.read_csv("2007-2018-HIC-Counts-by-State_2009.csv").rename(columns={'Total Year-Round Beds (ES,TH,SH)':'Total Beds 2009','HMIS Participation Rate (ES,TH,SH)':'Participation 2009'})
# Sh10_df = pd.read_csv("2007-2018-HIC-Counts-by-State_2010.csv").rename(columns={'Total Year-Round Beds (ES,TH,SH)':'Total Beds 2010','HMIS Participation Rate (ES,TH,SH)':'Participation 2010'})
# Sh11_df = pd.read_csv("2007-2018-HIC-Counts-by-State_2011.csv").rename(columns={'Total Year-Round Beds (ES,TH,SH)':'Total Beds 2011','HMIS Participation Rate (ES,TH,SH)':'Participation 2011'})
# Sh12_df = pd.read_csv("2007-2018-HIC-Counts-by-State_2012.csv").rename(columns={'Total Year-Round Beds (ES,TH,RRH,SH)':'Total Beds 2012','HMIS Participation Rate (ES,TH,RRH,SH)':'Participation 2012'})
# Sh13_df = pd.read_csv("2007-2018-HIC-Counts-by-State_2013.csv").rename(columns={'Total Year-Round Beds (ES,TH,SH)':'Total Beds 2013','HMIS Participation Rate (ES,TH,SH)':'Participation 2013'})
# Sh14_df = pd.read_csv("2007-2018-HIC-Counts-by-State_2014.csv").rename(columns={'Total Year-Round Beds (ES,TH,SH)':'Total Beds 2014','HMIS Participation Rate (ES,TH,SH)':'Participation 2014'})
# Sh15_df = pd.read_csv("2007-2018-HIC-Counts-by-State_2015.csv").rename(columns={'Total Year-Round Beds (ES,TH,SH)':'Total Beds 2015','HMIS Participation Rate (ES,TH,SH)':'Participation 2015'})
# Sh16_df = pd.read_csv("2007-2018-HIC-Counts-by-State_2016.csv").rename(columns={'Total Year-Round Beds (ES,TH,SH)':'Total Beds 2016','HMIS Participation Rate (ES,TH,SH)':'Participation 2016'})
# Sh17_df = pd.read_csv("2007-2018-HIC-Counts-by-State_2017.csv").rename(columns={'Total Year-Round Beds (ES,TH,SH)':'Total Beds 2017','HMIS Participation Rate (ES,TH,SH)':'Participation 2017'})
# Sh18_df = pd.read_csv("2007-2018-HIC-Counts-by-State_2018.csv").rename(columns={'Total Year-Round Beds (ES,TH,SH)':'Total Beds 2018','HMIS Participation Rate (ES,TH,SH)':'Participation 2018'})

In [ ]:
# Sh09_df = Shelters_09_df.rename(columns={'Total Year-Round Beds (ES,TH,SH)':'Total Beds 2009','HMIS Participation Rate (ES,TH,SH)':'Participation 2009'})
# Sh10_df = Shelters_10_df.rename(columns={'Total Year-Round Beds (ES,TH,SH)':'Total Beds 2010','HMIS Participation Rate (ES,TH,SH)':'Participation 2010'})
# Sh11_df = Shelters_11_df.rename(columns={'Total Year-Round Beds (ES,TH,SH)':'Total Beds 2011','HMIS Participation Rate (ES,TH,SH)':'Participation 2011'})
# Sh12_df = Shelters_12_df.rename(columns={'Total Year-Round Beds (ES,TH,SH)':'Total Beds 2012','HMIS Participation Rate (ES,TH,SH)':'Participation 2012'})
# Sh13_df = Shelters_13_df.rename(columns={'Total Year-Round Beds (ES,TH,SH)':'Total Beds 2013','HMIS Participation Rate (ES,TH,SH)':'Participation 2013'})
# Sh14_df = Shelters_14_df.rename(columns={'Total Year-Round Beds (ES,TH,SH)':'Total Beds 2014','HMIS Participation Rate (ES,TH,SH)':'Participation 2014'})
# Sh15_df = Shelters_15_df.rename(columns={'Total Year-Round Beds (ES,TH,SH)':'Total Beds 2015','HMIS Participation Rate (ES,TH,SH)':'Participation 2015'})
# Sh16_df = Shelters_16_df.rename(columns={'Total Year-Round Beds (ES,TH,SH)':'Total Beds 2016','HMIS Participation Rate (ES,TH,SH)':'Participation 2016'})
# Sh17_df = Shelters_17_df.rename(columns={'Total Year-Round Beds (ES,TH,SH)':'Total Beds 2017','HMIS Participation Rate (ES,TH,SH)':'Participation 2017'})
# Sh18_df = Shelters_18_df.rename(columns={'Total Year-Round Beds (ES,TH,SH)':'Total Beds 2018','HMIS Participation Rate (ES,TH,SH)':'Participation 2018'})

In [67]:
# merged_year_df = combined_df5[['State','Total Beds 2009','Participation 2009','Total Beds 2010','Participation 2010','Total Beds 2011','Participation 2011','Total Beds 2012','Participation 2012,]]
# merged_year_df

In [68]:
#'Total Beds 2009', 'Participation 2009', 'Total Beds 2010', 'Participation 2010', 'Total Beds 2011', 'Participation 2011', 'Total Beds 2012', 'Participation 2012', 'Total Beds 2013', 'Participation 2013', 'Total Beds 2014', 'Participation 2014', 'Total Beds 2015', 'Participation 2015', 'Total Beds 2016', 'Participation 2016','Total Beds 2017', 'Participation 2017', 'Total Beds 2018', 'Participation 2018']]

In [ ]:
# Sh09_df = Sh09_df[["State", 'Total Beds 2009', 'Participation 2009' ]]
# Sh10_df = Sh10_df[["State", 'Total Beds 2010', 'Participation 2010' ]]
# Sh11_df = Sh11_df[["State", 'Total Beds 2011', 'Participation 2011' ]]
# Sh12_df = Sh12_df[["State", 'Total Beds 2012', 'Participation 2012' ]]
# Sh13_df = Sh13_df[["State", 'Total Beds 2013', 'Participation 2013' ]]
# Sh14_df = Sh14_df[["State", 'Total Beds 2014', 'Participation 2014' ]]
# Sh15_df = Sh15_df[["State", 'Total Beds 2015', 'Participation 2015' ]]
# Sh16_df = Sh16_df[["State", 'Total Beds 2016', 'Participation 2016' ]]
# Sh17_df = Sh17_df[["State", 'Total Beds 2017', 'Participation 2017' ]]
# Sh18_df = Sh18_df[["State", 'Total Beds 2018', 'Participation 2018' ]]

In [ ]:
# combined_F = pd.merge(combined_A, combined_B, on='State')
# combined_G= pd.merge(combined_C, combined_D, on='State')
# combined_H = pd.merge(combined_F, combined_G, on='State')

In [ ]:
# combined_years = pd.merge(combined_H, combined_E, on='State')

In [ ]:
# Shelters_11_df, Shelters_12_df, Shelters_13_df, Shelters_14_df, Shelters_15_df, Shelters_16_df, Shelters_17_df, Shelters_18_df

In [ ]:
# df_list0 = [Sh09_df, Sh10_df, Sh11_df]
# df_list2 = [Sh12_df, Sh13_df, Sh14_df]
# df_list3 = [Sh15_df, Sh16_df, Sh17_df]